Repository Solvro/mobile-umed, pull requests merged in 2025-05, with the labels that each got.

#33 feat: add landmark type
  ios/Podfile.lock
  lib/common/data_source/mocks/mock_routes.dart
  lib/common/models/landmark.dart
Labels: size/S

#32 feat: create colorScheme and textTheme
  .gitignore
  assets/fonts/Urbanist-Black.ttf
  assets/fonts/Urbanist-Bold.ttf
  assets/fonts/Urbanist-ExtraBold.ttf
  assets/fonts/Urbanist-ExtraLight.ttf
  assets/fonts/Urbanist-Light.ttf
  assets/fonts/Urbanist-Medium.ttf
  assets/fonts/Urbanist-Regular.ttf
  assets/fonts/Urbanist-Thin.ttf
  assets/images/.gitkeep
  lib/app/app.dart
  lib/app/theme/app_theme.dart
  lib/app/theme/color_consts.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#36 feat: route screen
  assets/icons/checkmark.svg
  assets/icons/checkpointInactive.svg
  assets/icons/checkpointUnvisited.svg
  assets/icons/checkpointVisited.svg
  assets/icons/finishActive.svg
  assets/icons/finishInactive.svg
  assets/icons/pulsometerActive.svg
  assets/icons/pulsometerInactive.svg
  assets/icons/startActive.svg
  assets/icons/startInactive.svg
  lib/app/config/flutter_map_config.dart
  lib/app/config/ui_config.dart
  lib/app/l10n/arb/app_pl.arb
  lib/app/theme/app_theme.dart
  lib/common/data_source/mocks/mock_routes.dart
  lib/common/data_source/mocks/mock_songs.dart
  lib/common/models/song.dart
  lib/common/providers/bottom_sheet_providers.dart
  lib/common/widgets/info_modal.dart
  lib/common/widgets/main_action_button.dart
  lib/common/widgets/map_bottom_sheet.dart
  lib/common/widgets/options_modal.dart
  lib/common/widgets/secondary_action_button.dart
  lib/common/widgets/sheet_top_handle.dart
  lib/features/home/views/home_view.dart
  lib/features/route_map/controllers/route_controller.dart
  lib/features/route_map/repository/route_map_repository.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/playlist_info_section.dart
  lib/features/route_map/widgets/bottom_sheet/route_info_section.dart
  lib/features/route_map/widgets/bottom_sheet/song_tile.dart
  lib/features/route_map/widgets/map/route_map_marker.dart
  lib/features/route_map/widgets/map/route_map_polyline.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  lib/features/route_map/widgets/modals/end_route_modal.dart
  lib/features/route_map/widgets/modals/landmark_info_modal.dart
  lib/features/route_map/widgets/modals/route_completed_modal.dart
  lib/features/route_map/widgets/modals/stat_info_compact.dart
  lib/features/route_map/widgets/progress_bar/route_progress_bar.dart
  lib/features/route_map/widgets/progress_bar/route_progress_bar_icon.dart
  lib/features/route_map/widgets/progress_bar/route_progress_bar_line.dart
Labels: size/XXL

#39 feat: nav bar
  lib/app/config/ui_config.dart
  lib/app/router.dart
  lib/app/theme/app_theme.dart
  lib/app/theme/color_consts.dart
  lib/common/widgets/info_modal.dart
  lib/common/widgets/map_bottom_sheet.dart
  lib/common/widgets/options_modal.dart
  lib/common/widgets/sheet_top_handle.dart
  lib/features/dashboard/dashboard_page.dart
  lib/features/dashboard/widgets/nav_bar.dart
  lib/features/route_map/widgets/modals/end_route_modal.dart
  lib/features/route_map/widgets/progress_bar/route_progress_bar.dart
Labels: enhancement, size/L

#35 feat: add route map hive cache
  lib/common/extensions/path_provider.dart
  lib/features/route_map/repository/route_map_repository.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L
