Repository Solvro/mobile-umed, pull requests merged in 2025-08, with the labels that each got.

#131 fix: add new icons
  assets/icons/email.svg
  assets/icons/facebook.svg
  assets/icons/github.svg
  assets/icons/internet.svg
  assets/icons/linkedin.svg
  lib/features/info/widgets/socials_section.dart
Labels: size/S

#132 fix: pre-beta fixes
  .fvmrc
  lib/app/config/ui_config.dart
  lib/app/l10n/arb/app_pl.arb
  lib/common/models/completed_route.dart
  lib/common/models/creator.dart
  lib/common/models/info_section.dart
  lib/common/models/playlist.dart
  lib/common/providers/completed_routes_provider.dart
  lib/common/widgets/app_bar.dart
  lib/features/debug_playground/widgets/shimmer_test_widget.dart
  lib/features/home/home_page.dart
  lib/features/home/views/home_view.dart
  lib/features/info/info_page.dart
  lib/features/info/repository/info_repository.dart
  lib/features/info/repository/info_repository_helpers.dart
  lib/features/info/views/info_view.dart
  lib/features/info/widgets/creator_tile/creator_tile.dart
  lib/features/profile/profile_page.dart
  lib/features/profile/views/profile_view.dart
  lib/features/route_map/route_map_page.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/route_bottom_sheet.dart
  lib/features/route_map/widgets/bottom_sheet/sections/playlist_info_section.dart
  lib/features/route_map/widgets/bottom_sheet/sections/song_tile.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_tile.dart
Labels: size/L

#138 feat: change app name and fix issues with images
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/app/app.dart
  lib/app/config/cached_image_config.dart
  lib/common/widgets/horizontal_routes_list/route_card.dart
  lib/features/info/widgets/creator_tile/creator_tile.dart
Labels: size/S

#145 fix: creators image aspect ratio
  lib/features/info/widgets/creator_tile/creator_tile.dart
Labels: size/S

#149 fix: fixes
  lib/app/app.dart
  lib/app/config/ui_config.dart
  lib/features/route_map/modals/end_route_modal.dart
  lib/features/route_map/modals/landmark_info_modal.dart
  lib/features/route_map/modals/start_route_modal.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/route_bottom_sheet.dart
  pubspec.yaml
Labels: size/M

#139 feat: clear dio cache
  ios/Podfile.lock
  lib/app/app.dart
  lib/common/data_source/remote/cache_options.dart
  lib/common/data_source/remote/no_cache_dio_client.dart
  lib/common/repositories/cache_ref_repository.dart
  lib/common/utils/storage_service.dart
  lib/features/home/home_page.dart
  lib/features/route_map/services/task_handlers/route_foreground_task_handler.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#155 fix: color and bottom sheet
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/app/theme/color_consts.dart
  lib/common/models/socials.dart
  lib/common/widgets/styling/sheet_top_handle.dart
  lib/features/info/widgets/socials_section.dart
  lib/features/profile/views/profile_view.dart
Labels: size/M

#156 fix: polish signs in sans-serif
  assets/fonts/Urbanist-SemiBold.ttf
  lib/app/theme/app_theme.dart
  pubspec.yaml
Labels: size/XS

#165 feat: custom toast for error
  lib/app/l10n/arb/app_pl.arb
  lib/common/utils/url_launcher.dart
  lib/features/error/widgets/error_snack_bar.dart
  lib/features/route_map/route_map_page.dart
  lib/features/route_map/widgets/bottom_sheet/sections/playlist_info_section.dart
Labels: size/M

#167 feat: add stats to map view
  lib/common/models/route_stats.dart
  lib/common/models/song.dart
  lib/common/parsers/duration_converter.dart
  lib/common/widgets/app_bar.dart
  lib/features/map/route_map/controllers/route_controller.dart
  lib/features/map/route_map/providers/route_stats_provider.dart
  lib/features/map/route_map/route_map_page.dart
  lib/features/map/route_map/services/task_handlers/foreground_task_protocol.dart
  lib/features/map/route_map/services/task_handlers/foreground_task_service.dart
  lib/features/map/route_map/services/task_handlers/route_foreground_task_handler.dart
  lib/features/map/route_map/widgets/bottom_sheet/sections/route_info_section.dart
  lib/features/map/route_map/widgets/map/route_map_widget.dart
Labels: size/L
