Repository Solvro/mobile-umed, pull requests merged in 2025-04, with the labels that each got.

#3 fix: config
  .github/workflows/flutter_ci.yaml
  .gitignore
  analysis_options.yaml
  l10n.yaml
  lib/app/app.dart
  lib/app/l10n/arb/app_en.arb
  lib/app/l10n/l10n.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: size/L

#5 feat: route and checkpoint models
  lib/common/models/landmark.dart
  lib/common/models/route.dart
  lib/common/parsers/latlng_converter.dart
  pubspec.lock
  pubspec.yaml
Labels: size/M

#13 feat(navigation): implement basic routes and navbar
  commitlint.yaml
  lib/app/app.dart
  lib/app/router.dart
  lib/features/achievements/achievements_page.dart
  lib/features/dashboard/dashboard_page.dart
  lib/features/home/home_page.dart
  lib/features/others/others_page.dart
Labels: enhancement, good first issue, size/L

#15 feat: add image caching widget
  assets/images/no_image.png
  lib/app/config/cached_image_config.dart
  lib/common/widgets/cached_image.dart
  lib/common/widgets/no_image_placeholder.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#20 feat: create dio client and api providers
  ios/Runner.xcodeproj/project.pbxproj
  lib/common/data_source/mocks/mock_routes.dart
  lib/common/data_source/remote/dio_client.dart
  lib/common/models/route.dart
  lib/common/parsers/landmark_list_converter.dart
  lib/features/home/views/home_view.dart
  lib/features/route_map/repository/route_map_repository.dart
  test/widget_test.dart
Labels: size/L

#23 feat: cache
  ios/Podfile.lock
  lib/common/data_source/remote/README.md
  lib/common/data_source/remote/cache_options.dart
  lib/common/data_source/remote/dio_client.dart
  lib/features/route_map/repository/route_map_repository.dart
  pubspec.lock
  pubspec.yaml
  test/cache_tests.dart
Labels: size/L

#25 feat: create README.md
  README.md
Labels: size/M
