Repository Solvro/mobile-umed, pull requests merged in 2025-07, with the labels that each got.

#70 feat: select route screen 2
  assets/icons/kcal.svg
  assets/icons/time.svg
  assets/icons/water.svg
  ios/Podfile.lock
  lib/app/config/ui_config.dart
  lib/app/l10n/arb/app_pl.arb
  lib/app/router.dart
  lib/app/theme/color_consts.dart
  lib/common/data_source/mocks/mock_routes.dart
  lib/common/models/route.dart
  lib/common/widgets/list_label.dart
  lib/common/widgets/map_bottom_sheet.dart
  lib/common/widgets/secondary_action_button.dart
  lib/common/widgets/sheet_top_handle.dart
  lib/features/debug_playground/debug_playground.dart
  lib/features/route_map/controllers/route_controller.dart
  lib/features/route_map/providers/route_provider.dart
  lib/features/route_map/route_map_page.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/route_bottom_sheet.dart
  lib/features/route_map/widgets/bottom_sheet/sections/landmarks_section.dart
  lib/features/route_map/widgets/bottom_sheet/sections/playlist_info_section.dart
  lib/features/route_map/widgets/bottom_sheet/sections/route_info_section.dart
  lib/features/route_map/widgets/bottom_sheet/sections/song_tile.dart
  lib/features/route_map/widgets/bottom_sheet/select_route_bottom_sheet.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/landmark_item.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_stat.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_tile.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  lib/features/route_map/widgets/modals/start_route_modal.dart
Labels: size/XL

#76 feat: save stats using hive
  ios/Podfile.lock
  lib/app/app.dart
  lib/app/config/ui_config.dart
  lib/app/l10n/arb/app_pl.arb
  lib/common/models/completed_route.dart
  lib/common/models/route.dart
  lib/common/parsers/completed_routes_stats_converter.dart
  lib/common/providers/completed_routes_provider.dart
  lib/features/debug_playground/debug_playground.dart
  lib/features/profile/views/profile_view.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_stat.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_tile.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#84 feat: display routes on map when selecting
  ios/Podfile.lock
  lib/features/route_map/providers/route_provider.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_tile.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  lib/features/route_map/widgets/map/route_selections_polyline.dart
  lib/features/route_map/widgets/modals/start_route_modal.dart
  lib/main.dart
Labels: size/M

#83 feat: landmark popup
  ios/Podfile.lock
  lib/app/config/ui_config.dart
  lib/app/l10n/arb/app_pl.arb
  lib/common/data_source/mocks/mock_routes.dart
  lib/common/models/landmark.dart
  lib/common/widgets/common/label_value_pair.dart
  lib/features/debug_playground/debug_playground.dart
  lib/features/route_map/modals/end_route_modal.dart
  lib/features/route_map/modals/landmark_info_modal.dart
  lib/features/route_map/modals/route_completed_modal.dart
  lib/features/route_map/modals/start_route_modal.dart
  lib/features/route_map/modals/stat_info_compact.dart
  lib/features/route_map/widgets/bottom_sheet/route_bottom_sheet.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_stat.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_tile.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  lib/features/route_map/widgets/modals/landmark_info_modal.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#89 feat: Add map animations while centeringToMarker
  ios/Podfile.lock
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#90 feat: use router everywhere
  lib/app/l10n/arb/app_pl.arb
  lib/app/router.dart
  lib/common/utils/url_launcher.dart
  lib/common/widgets/common/horizontal_routes_list/horizontal_routes_list.dart
  lib/common/widgets/home/button_row.dart
  lib/common/widgets/home/start_route_button.dart
  lib/features/debug_playground/widgets/shimmer_test_widget.dart
  lib/features/error/views/full_screen_error_view.dart
  lib/features/home/home_page.dart
  lib/features/home/views/home_view.dart
  lib/features/info/views/info_view.dart
  lib/features/info/widgets/social_icon_button.dart
  lib/features/profile/profile_page.dart
  lib/features/profile/views/profile_view.dart
Labels: size/L

#93 fix: update models
  lib/app/config/ui_config.dart
  lib/app/l10n/arb/app_pl.arb
  lib/common/data_source/mocks/mock_routes.dart
  lib/common/models/checkpoint.dart
  lib/common/models/route.dart
  lib/common/parsers/landmark_list_converter.dart
  lib/features/route_map/controllers/route_controller.dart
  lib/features/route_map/modals/landmark_info_modal.dart
  lib/features/route_map/modals/start_route_modal.dart
  lib/features/route_map/providers/route_provider.dart
  lib/features/route_map/repository/route_map_repository.dart
  lib/features/route_map/route_map_page.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/sections/landmarks_section.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/landmark_item.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_tile.dart
  lib/features/route_map/widgets/map/route_map_marker.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  lib/features/route_map/widgets/progress_bar/route_progress_bar.dart
Labels: size/L

#110 feat: wiredash
  .env
  example.env
  lib/app/config/env.dart
  lib/app/wiredash.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: size/M

#112 feat: ask before exiting route using phone's navigation
  ios/Podfile.lock
  lib/common/utils/modal_before_exiting.dart
  lib/features/route_map/modals/end_route_modal.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/route_bottom_sheet.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
Labels: size/L

#113 fix: change start and finish logic to be based on enum type
  lib/features/route_map/widgets/map/route_map_marker.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
Labels: size/M

#104 fix: add Media query to position the center button
  lib/features/route_map/views/route_map_view.dart
Labels: size/XS

#103 feat: fix route card title
  lib/common/widgets/common/horizontal_routes_list/route_card.dart
Labels: size/M

#118 fix: url launcher
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/common/utils/url_launcher.dart
Labels: size/S

#121 fix: cached image null error
  lib/common/widgets/common/horizontal_routes_list/route_card.dart
Labels: size/XS

#120 refactor: show only expanded routes on map
  lib/features/route_map/providers/route_provider.dart
  lib/features/route_map/route_map_page.dart
  lib/features/route_map/views/route_map_view.dart
  lib/features/route_map/widgets/bottom_sheet/tiles/route_tile.dart
  lib/features/route_map/widgets/map/route_map_widget.dart
  lib/features/route_map/widgets/map/route_selections_polyline.dart
Labels: size/M

#126 fix: info page styling
  assets/icons/sectionTitleDecoration.svg
  lib/app/config/ui_config.dart
  lib/features/info/views/info_view.dart
  lib/features/info/widgets/section_title.dart
Labels: size/M

#125 feat: show modals if accessing map without permissions
  ios/Podfile.lock
  lib/app/app.dart
  lib/app/l10n/arb/app_pl.arb
  lib/app/router.dart
  lib/common/utils/location_service.dart
  lib/common/widgets/info_modal.dart
  lib/common/widgets/location_access_modal.dart
Labels: size/M

#128 chore: change to type safe svg path
  lib/common/widgets/app_bar.dart
  lib/common/widgets/modals/info_modal.dart
  lib/features/home/views/home_view.dart
  lib/features/info/widgets/text_info_tile.dart
  lib/features/route_map/modals/landmark_info_modal.dart
  lib/features/route_map/modals/stat_info_compact.dart
  lib/features/route_map/widgets/bottom_sheet/route_bottom_sheet.dart
  lib/features/route_map/widgets/bottom_sheet/sections/song_tile.dart
Labels: size/S
