Repository Solvro/mobile-umed, pull requests merged in 2025-09, with the labels that each got.

#186 refactor: improve layout and structure of RouteTile widget
  lib/features/map/multi_route_map/widgets/select_route_bottom_sheet.dart
  lib/features/map/route_map/widgets/bottom_sheet/tiles/route_tile.dart
Labels: size/L

#191 fix: start timer on reaching route
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/features/map/route_map/route_map_page.dart
  lib/features/map/route_map/services/task_handlers/route_foreground_task_handler.dart
Labels: size/L

#194 feat: change tracking logic
  lib/features/map/route_map/services/task_handlers/route_foreground_task_handler.dart
Labels: size/S

#199 fix: linek fixes
  ios/Podfile.lock
  lib/app/config/ui_config.dart
  lib/common/providers/cache_tile.dart
  lib/common/utils/location_service.dart
  lib/features/map/route_map/repository/route_map_repository.dart
  lib/features/map/route_map/services/task_handlers/route_foreground_task_handler.dart
  lib/main.dart
  pubspec.yaml
Labels: size/M
